version: '3.8'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - internal

  app:
    container_name: app
    build:
      context: ./docker/php
    environment:
      - PHP_IDE_CONFIG=serverName=docker
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - '9000:9000'
    volumes:
      - .:/var/www/app
    depends_on:
      - mysql
    networks:
      - internal

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '80:80'
    volumes:
      - .:/var/www/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - mysql
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  db-data:
    driver: local
